const data = {
  "status": "OK",
  "request_id": "81a93af3-8836-4f32-a01c-416a574cc4a0",
  "data": {
    "total_products": 9985,
    "country": "US",
    "domain": "www.amazon.com",
    "products": {
      "phones": [
        {
          "asin": "B0BQ118F2T",
          "product_title": "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera",
          "product_price": "$99.99",
          "product_original_price": "$169.99",
          "currency": "USD",
          "product_star_rating": "4",
          "product_num_ratings": 2740,
          "product_url": "https://www.amazon.com/dp/B0BQ118F2T",
          "product_photo": "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 22,
          "product_minimum_offer_price": "$72.06",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J5F3G18",
          "product_title": "Samsung Galaxy S21 5G | Factory Unlocked Android Cell Phone",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 19000,
          "product_url": "https://www.amazon.com/dp/B08J5F3G18",
          "product_photo": "https://m.media-amazon.com/images/I/81kfA-GtWwL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 35,
          "product_minimum_offer_price": "$649.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08L5TNJHG",
          "product_title": "Apple iPhone 12 Pro Max, 256GB, Graphite - Fully Unlocked (Renewed)",
          "product_price": "$1049.99",
          "product_original_price": "$1199.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 5000,
          "product_url": "https://www.amazon.com/dp/B08L5TNJHG",
          "product_photo": "https://m.media-amazon.com/images/I/71XXJC7V8tL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$999.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B09RWQHBQT",
          "product_title": "OnePlus 9 Pro, 5G Unlocked Android Smartphone U.S. Version",
          "product_price": "$899.99",
          "product_original_price": "$969.99",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B09RWQHBQT",
          "product_photo": "https://m.media-amazon.com/images/I/612ytK4luvL._SL1500_.jpg",
          "product_num_offers": 28,
          "product_minimum_offer_price": "$849.99",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08N2MSSZY",
          "product_title": "Google Pixel 5 - 5G Android Phone with extra zooming",
          "product_price": "$699.00",
          "product_original_price": "$799.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 4300,
          "product_url": "https://www.amazon.com/dp/B08N2MSSZY",
          "product_photo": "https://www.chooseyourmobile.com/wp-content/uploads/2020/10/Google-Pixel-5-Sorta-Sage-Colors.jpg",
          "product_num_offers": 21,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08P2H5LW2",
          "product_title": "Sony Xperia 1 II 5G Unlocked Smartphone with IP68 fully waterproof",
          "product_price": "$1198.00",
          "product_original_price": "$1299.99",
          "currency": "USD",
          "product_star_rating": "4.2",
          "product_num_ratings": 2100,
          "product_url": "https://www.amazon.com/dp/B08P2H5LW2",
          "product_photo": "https://cdn.shopify.com/s/files/1/0077/5513/7083/products/2526caa2-d3fe-4699-8f15-5b9998ff6147_2048x.jpg?v=1641829889",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$1150.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B085X6DJTQ",
          "product_title": "LG V60 ThinQ 5G Dual Screen (128GB, 8GB RAM) 6.8\" OLED",
          "product_price": "$749.99",
          "product_original_price": "$899.99",
          "currency": "USD",
          "product_star_rating": "4.1",
          "product_num_ratings": 1400,
          "product_url": "https://www.amazon.com/dp/B085X6DJTQ",
          "product_photo": "https://microless.com/cdn/products/6aacb66173e5b4ba1008eaf695eb1181-hi.jpg",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$720.00",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07D9XJJ37",
          "product_title": "Nokia 6.1 Plus (64GB, 4GB RAM) 5.8\" Display, Dual SIM 4G LTE",
          "product_price": "$229.99",
          "product_original_price": "$259.99",
          "currency": "USD",
          "product_star_rating": "4.0",
          "product_num_ratings": 3200,
          "product_url": "https://www.amazon.com/dp/B07D9XJJ37",
          "product_photo": "https://www.rvcj.com/wp-content/uploads/2019/07/nokia-6.1.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$210.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07QK9KJW6",
          "product_title": "Huawei P30 Pro 128GB + 8GB RAM, 6.47\" OLED Display",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 3500,
          "product_url": "https://www.amazon.com/dp/B07QK9KJW6",
          "product_photo": "https://images-na.ssl-images-amazon.com/images/I/61XM1qbUPUL._SL1000_.jpg",
          "product_num_offers": 14,
          "product_minimum_offer_price": "$650.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B083VM8G8V",
          "product_title": "Xiaomi Mi Note 10 Pro 256GB + 8GB RAM, 6.47\" AMOLED Display",
          "product_price": "$529.99",
          "product_original_price": "$599.99",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 2300,
          "product_url": "https://www.amazon.com/dp/B083VM8G8V",
          "product_photo": "https://th.bing.com/th/id/OIP.MXG5NKpCI_bu3YSRZwnlDgAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 16,
          "product_minimum_offer_price": "$500.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other phone products here
      ],
      "shoes": [
        {
          "asin": "B07PGL2ZSL",
          "product_title": "Nike Men's Air Max 270 Shoes",
          "product_price": "$150.00",
          "product_original_price": "$180.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 1020,
          "product_url": "https://www.amazon.com/dp/B07PGL2ZSL",
          "product_photo": "https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/hyn4my0yzq35ol3gpdsa/air-max-270-shoe-nnTrqDGR.jpg",
          "product_num_offers": 5,
          "product_minimum_offer_price": "$140.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08VJKYQKL",
          "product_title": "Adidas Men's Ultraboost 21 Running Shoe",
          "product_price": "$180.00",
          "product_original_price": "$200.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 12000,
          "product_url": "https://www.amazon.com/dp/B08VJKYQKL",
          "product_photo": "https://therunningoutlet.co.uk/wp-content/uploads/2021/07/adidas-mens-ultra-boost-21-S23863-side.jpg",
          "product_num_offers": 28,
          "product_minimum_offer_price": "$160.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07NJ8P1TX",
          "product_title": "ASICS Men's Gel-Venture 7 Running Shoes",
          "product_price": "$70.00",
          "product_original_price": "$80.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 8300,
          "product_url": "https://www.amazon.com/dp/B07NJ8P1TX",
          "product_photo": "https://th.bing.com/th/id/OIP.saqI85HYJ9o5maKpAl0eUAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 22,
          "product_minimum_offer_price": "$65.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07NNS7X9L",
          "product_title": "New Balance Men's 574 V2 Evergreen Sneaker",
          "product_price": "$85.00",
          "product_original_price": "$90.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4500,
          "product_url": "https://www.amazon.com/dp/B07NNS7X9L",
          "product_photo": "https://th.bing.com/th/id/OIP.WNbtfVIZGLy8REDFDl2h9wHaFP?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$80.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07QK7N9L9",
          "product_title": "Puma Men's Tazon 6 FM Running Shoe with comfort",
          "product_price": "$65.00",
          "product_original_price": "$75.00",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 6300,
          "product_url": "https://www.amazon.com/dp/B07QK7N9L9",
          "product_photo": "https://th.bing.com/th/id/OIP.YAChyTTifQqVUG9EluAcqQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$60.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J5VKNLY",
          "product_title": "Under Armour Men's Charged Assert 8 Running Shoe",
          "product_price": "$70.00",
          "product_original_price": "$75.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9700,
          "product_url": "https://www.amazon.com/dp/B08J5VKNLY",
          "product_photo": "https://m.media-amazon.com/images/I/51fjQKot6RL.jpg",
          "product_num_offers": 25,
          "product_minimum_offer_price": "$65.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "9K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07QQTW9M4",
          "product_title": "Reebok Men's Club C 85 Vintage Running Shoe",
          "product_price": "$75.00",
          "product_original_price": "$85.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 7800,
          "product_url": "https://www.amazon.com/dp/B07QQTW9M4",
          "product_photo": "https://th.bing.com/th/id/OIP.KffE2LgUp84MSVLg_WOG4wHaFj?rs=1&pid=ImgDetMain",
          "product_num_offers": 23,
          "product_minimum_offer_price": "$70.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08T1XXB8Y",
          "product_title": "Skechers Men's Energy Afterburn Lace-Up Sneaker",
          "product_price": "$55.00",
          "product_original_price": "$65.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 10200,
          "product_url": "https://www.amazon.com/dp/B08T1XXB8Y",
          "product_photo": "https://th.bing.com/th/id/OIP.85crmNDkwuQTmuXZuStoKgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 27,
          "product_minimum_offer_price": "$50.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "11K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08NNN5WXS",
          "product_title": "Converse Chuck Taylor All Star Low Top Sneaker",
          "product_price": "$55.00",
          "product_original_price": "$60.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 8600,
          "product_url": "https://www.amazon.com/dp/B08NNN5WXS",
          "product_photo": "https://th.bing.com/th/id/OIP.dGHdWwjkKLhupFZYgS6R-QHaFP?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$50.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "9K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07QFJLL5M",
          "product_title": "Fila Men's Disruptor II Sneaker",
          "product_price": "$60.00",
          "product_original_price": "$70.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9200,
          "product_url": "https://www.amazon.com/dp/B07QFJLL5M",
          "product_photo": "https://th.bing.com/th/id/OIP.Oi15wIPciQNgl5C76CAXmAHaFP?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$55.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
      ],
      // cloths 
      "clothes": [
        {
          "asin": "B08D9X3HTF",
          "product_title": "Levi's Men's 511 Slim Fit Jeans for great styling",
          "product_price": "$50.00",
          "product_original_price": "$60.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 13400,
          "product_url": "https://www.amazon.com/dp/B08D9X3HTF",
          "product_photo": "https://th.bing.com/th/id/OIP.3quiXDyoTBWaox7HqXnFwQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 25,
          "product_minimum_offer_price": "$45.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07JHLS6LC",
          "product_title": "Hanes Men's EcoSmart Fleece Sweatshirt for winter",
          "product_price": "$12.00",
          "product_original_price": "$15.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 19300,
          "product_url": "https://www.amazon.com/dp/B07JHLS6LC",
          "product_photo": "https://th.bing.com/th/id/OIP.d0NBI3L0-pVmVLbriRtWiAHaJ4?rs=1&pid=ImgDetMain",
          "product_num_offers": 22,
          "product_minimum_offer_price": "$10.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "15K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07MZ9MLPB",
          "product_title": "Amazon Essentials Men's Regular-Fit Long-Sleeve Flannel Shirt",
          "product_price": "$20.00",
          "product_original_price": "$25.00",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 7500,
          "product_url": "https://www.amazon.com/dp/B07MZ9MLPB",
          "product_photo": "https://images-na.ssl-images-amazon.com/images/I/91c568PCvbL.jpg",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$18.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B084V47FG7",
          "product_title": "Champion Men's Powerblend Fleece Pullover Hoodie",
          "product_price": "$40.00",
          "product_original_price": "$50.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 10300,
          "product_url": "https://www.amazon.com/dp/B084V47FG7",
          "product_photo": "https://th.bing.com/th/id/OIP.nmeLakXYOGBXFGgxSxTpxgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$35.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "12K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08DHRHTHS",
          "product_title": "Columbia Men's Steens Mountain 2.0 Full Zip Fleece Jacket",
          "product_price": "$35.00",
          "product_original_price": "$40.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9400,
          "product_url": "https://www.amazon.com/dp/B08DHRHTHS",
          "product_photo": "https://th.bing.com/th/id/OIP.t_7186EP1z0PqZEHvLWKDgHaJB?rs=1&pid=ImgDetMain",
          "product_num_offers": 17,
          "product_minimum_offer_price": "$30.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "11K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07YZ4XSG5",
          "product_title": "Nike Men's Sportswear Club Fleece Jogger Pants",
          "product_price": "$55.00",
          "product_original_price": "$65.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 4100,
          "product_url": "https://www.amazon.com/dp/B07YZ4XSG5",
          "product_photo": "https://th.bing.com/th/id/OIP.0jpruCATNX5aD80tnlJczQHaJQ?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$50.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08GFRS56K",
          "product_title": "Calvin Klein Men's Cotton Classics Multipack Boxer Briefs",
          "product_price": "$28.99",
          "product_original_price": "$39.50",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 6800,
          "product_url": "https://www.amazon.com/dp/B08GFRS56K",
          "product_photo": "https://images-na.ssl-images-amazon.com/images/I/51HxNKJ1noL.jpg",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$26.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07QSD6NQD",
          "product_title": "Adidas Men's Tiro 19 Training Pants for better comfort",
          "product_price": "$34.99",
          "product_original_price": "$45.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 4900,
          "product_url": "https://www.amazon.com/dp/B07QSD6NQD",
          "product_photo": "https://th.bing.com/th/id/OIP.gP9exvsr2iOQ8uMSNVxcUgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$31.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07X5J63J2",
          "product_title": "Under Armour Men's Tech 2.0 Short Sleeve T-Shirt",
          "product_price": "$19.99",
          "product_original_price": "$25.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5800,
          "product_url": "https://www.amazon.com/dp/B07X5J63J2",
          "product_photo": "https://th.bing.com/th/id/OIP.CYpyq6iy3sU5VKPh_6SPIgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$17.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "9K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07KZ63K6B",
          "product_title": "Carhartt Men's Acrylic Watch Hat A18",
          "product_price": "$16.99",
          "product_original_price": "$19.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 7800,
          "product_url": "https://www.amazon.com/dp/B07KZ63K6B",
          "product_photo": "https://th.bing.com/th/id/OIP.XMOmLegNLlAekjgv9GgfwgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$15.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other clothes products here
      ],
      "watches": [
        {
          "asin": "B07W7Y62G7",
          "product_title": "Fossil Men's Gen 5E 44mm Stainless Steel Touchscreen Smartwatch",
          "product_price": "$129.99",
          "product_original_price": "$199.00",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 1400,
          "product_url": "https://www.amazon.com/dp/B07W7Y62G7",
          "product_photo": "https://th.bing.com/th/id/OIP.4gHEEru5LCHUt8b1sZj8jQHaEv?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$120.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08HZKDV1J",
          "product_title": "Samsung Galaxy Watch Active 2 (44mm, GPS, Bluetooth) Smart Watch",
          "product_price": "$219.99",
          "product_original_price": "$269.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 2800,
          "product_url": "https://www.amazon.com/dp/B08HZKDV1J",
          "product_photo": "https://th.bing.com/th/id/OIP.Z7LjHH890V3HKOfnsPPJJQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$199.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07W6Q1WVG",
          "product_title": "Garmin Forerunner 245 Music, GPS Running Smartwatch",
          "product_price": "$299.99",
          "product_original_price": "$349.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 1800,
          "product_url": "https://www.amazon.com/dp/B07W6Q1WVG",
          "product_photo": "https://th.bing.com/th/id/OIP.AYEwTNZfVj6LjBQ4nl4ZQQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$289.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J63FMXL",
          "product_title": "Fitbit Versa 3 Health & Fitness Smartwatch  Touchscreen Smartwatch",
          "product_price": "$229.95",
          "product_original_price": "$249.95",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 3200,
          "product_url": "https://www.amazon.com/dp/B08J63FMXL",
          "product_photo": "https://th.bing.com/th/id/OIP.BQt503ki9b58GPDEhA-WGgAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$219.95",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08G9P51G6",
          "product_title": "Apple Watch Series 6 (GPS, 44mm) - Space Gray Aluminum Case",
          "product_price": "$409.00",
          "product_original_price": "$429.00",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 4600,
          "product_url": "https://www.amazon.com/dp/B08G9P51G6",
          "product_photo": "https://th.bing.com/th/id/OIP.rkV1np8nBTYZkZFsVAr4TQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$399.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07ZDRD5Y7",
          "product_title": "Amazfit Bip U Pro Smart Watch with Built-in GPS",
          "product_price": "$69.99",
          "product_original_price": "$79.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B07ZDRD5Y7",
          "product_photo": "https://th.bing.com/th/id/OIP.9VjUJ5RETkYAPuiYPA9pJQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$65.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07WMM9C2Q",
          "product_title": "Citizen Eco-Drive Promaster Diver Watch, Stylish and fo formal",
          "product_price": "$179.99",
          "product_original_price": "$250.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 3200,
          "product_url": "https://www.amazon.com/dp/B07WMM9C2Q",
          "product_photo": "https://th.bing.com/th/id/OIP.MOQO0z-9F8wzB8POHK7VbwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$169.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08G8JN3HS",
          "product_title": "Michael Kors Access Gen 5 Bradshaw Smartwatch",
          "product_price": "$297.49",
          "product_original_price": "$350.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 1800,
          "product_url": "https://www.amazon.com/dp/B08G8JN3HS",
          "product_photo": "https://th.bing.com/th/id/OIP.Kspqz7avELMPtDEf4_1TSgHaJx?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$289.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08JQ8RVSD",
          "product_title": "Garmin Venu Sq - Music Edition, GPS Smartwatch with Bright Touchscreen ",
          "product_price": "$199.99",
          "product_original_price": "$249.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 1500,
          "product_url": "https://www.amazon.com/dp/B08JQ8RVSD",
          "product_photo": "https://th.bing.com/th/id/OIP.4rxKwrnXIlGZBfVMGTyuqQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$189.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B087QJB6MZ",
          "product_title": "Timex Men's Weekender 40mm Watch",
          "product_price": "$32.24",
          "product_original_price": "$57.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 3500,
          "product_url": "https://www.amazon.com/dp/B087QJB6MZ",
          "product_photo": "https://i5.walmartimages.com/asr/53149854-5bc4-4e4f-a5ce-d41679d26763_1.877e645f5e997f917ba105febb82872d.jpeg",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$29.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07TJY5ZTT",
          "product_title": "Casio Men's G-Shock Quartz Watch",
          "product_price": "$69.95",
          "product_original_price": "$99.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4200,
          "product_url": "https://www.amazon.com/dp/B07TJY5ZTT",
          "product_photo": "https://th.bing.com/th/id/OIP.gA8-qOXpnmg4-_YDPdjfTAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$64.95",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other watches products here
      ],
      "furniture": [
        {
          "asin": "B07FJ7SMJ5",
          "product_title": "Zinus Shalini Upholstered Platform Bed Frame",
          "product_price": "$199.00",
          "product_original_price": "$249.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 8300,
          "product_url": "https://www.amazon.com/dp/B07FJ7SMJ5",
          "product_photo": "https://th.bing.com/th/id/OIP.vxFn8y0LR-QaR4tNsvJ2EQHaFF?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$189.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07G2QHF8R",
          "product_title": "Walker Edison Furniture Company Modern Farmhouse Buffet Sideboard",
          "product_price": "$294.99",
          "product_original_price": "$349.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5200,
          "product_url": "https://www.amazon.com/dp/B07G2QHF8R",
          "product_photo": "https://th.bing.com/th/id/OIP.vi7GXuhMHscr7PgOxbMxwgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$279.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07G4HSMFJ",
          "product_title": "Zinus Mia Modern Studio 14 Inch Platform 1500H Metal Bed Frame",
          "product_price": "$118.99",
          "product_original_price": "$149.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 9500,
          "product_url": "https://www.amazon.com/dp/B07G4HSMFJ",
          "product_photo": "https://m.media-amazon.com/images/I/81I+75tgvYS._AC_SL1500_.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$109.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08F3MMK9N",
          "product_title": "Ashley Furniture Signature Design - 12 Inch Chime Express Memory Foam Mattress",
          "product_price": "$262.00",
          "product_original_price": "$299.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 7800,
          "product_url": "https://www.amazon.com/dp/B08F3MMK9N",
          "product_photo": "https://th.bing.com/th/id/OIP.rn2MFU-5mCWcSsegZCegYwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$249.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07DDFPH41",
          "product_title": "Rivet Modern Wood Nesting Side Table for small work ",
          "product_price": "$129.00",
          "product_original_price": "$149.00",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 4300,
          "product_url": "https://www.amazon.com/dp/B07DDFPH41",
          "product_photo": "https://th.bing.com/th/id/OIP.jPcCuVLXM6vvrS_XI_6MbwAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$119.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07CVLKJ62",
          "product_title": "Christopher Knight Home Karen Traditional Chesterfield Loveseat Sofa",
          "product_price": "$574.99",
          "product_original_price": "$699.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 3600,
          "product_url": "https://www.amazon.com/dp/B07CVLKJ62",
          "product_photo": "https://m.media-amazon.com/images/I/41JtlG9IqfL._SL500_.jpg",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$549.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08B5WVSGQ",
          "product_title": "Homelegance Barrington Upholstered Accent Chair",
          "product_price": "$192.80",
          "product_original_price": "$219.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4200,
          "product_url": "https://www.amazon.com/dp/B08B5WVSGQ",
          "product_photo": "https://th.bing.com/th/id/OIP.DcePieM8DTRlksO-t1CTmAHaJC?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$179.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B085T2KFXJ",
          "product_title": "Yaheetech Lift Top Coffee Table with Hidden Storage Compartment",
          "product_price": "$129.99",
          "product_original_price": "$149.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5500,
          "product_url": "https://www.amazon.com/dp/B085T2KFXJ",
          "product_photo": "https://i.pinimg.com/originals/ed/fa/c6/edfac6d207ae1193982ea21569e1636d.jpg",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$119.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07ZB7MJDS",
          "product_title": "Furinno Turn-N-Tube 5-Tier Multipurpose Shelf Display Rack",
          "product_price": "$58.53",
          "product_original_price": "$89.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 6300,
          "product_url": "https://www.amazon.com/dp/B07ZB7MJDS",
          "product_photo": "https://furinno.b-cdn.net/wp-content/uploads/2021/08/810006770964.PT04-1024x1024.jpg",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$49.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B089KHFPH1",
          "product_title": "Ravenna Home Traditional Dining Buffet Cabinet",
          "product_price": "$299.99",
          "product_original_price": "$349.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 3700,
          "product_url": "https://www.amazon.com/dp/B089KHFPH1",
          "product_photo": "https://th.bing.com/th/id/OIP.xOH_TC-mC21HdgVQ3fOZcwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$279.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B089F2C61W",
          "product_title": "Modway Transmit Mid-Century Buffet Sideboard",
          "product_price": "$194.10",
          "product_original_price": "$219.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 4900,
          "product_url": "https://www.amazon.com/dp/B089F2C61W",
          "product_photo": "https://i.pinimg.com/originals/ef/bc/62/efbc62d87971fa0c8bf1e99b5494fd67.jpg",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$179.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other furniture products here
      ],
      "groceries": [
        {
          "asin": "B0899R3GH6",
          "product_title": "Quaker Oats Old Fashioned Oatmeal, 18 oz Canister",
          "product_price": "$3.99",
          "product_original_price": "$4.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 5400,
          "product_url": "https://www.amazon.com/dp/B0899R3GH6",
          "product_photo": "https://th.bing.com/th/id/OIP.-sd2q-D5kqEChGcfKa3CUwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$3.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B003ZXEB4Q",
          "product_title": "McCormick Gourmet Organic Ground Turmeric, 1.37 oz",
          "product_price": "$3.98",
          "product_original_price": "$4.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 3100,
          "product_url": "https://www.amazon.com/dp/B003ZXEB4Q",
          "product_photo": "https://th.bing.com/th/id/OIP.pYOc94QYLokSEbXgEzAPVwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$3.50",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B01H1R0K0M",
          "product_title": "Heinz Tomato Ketchup, 32 oz Bottle",
          "product_price": "$2.98",
          "product_original_price": "$3.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 7200,
          "product_url": "https://www.amazon.com/dp/B01H1R0K0M",
          "product_photo": "https://th.bing.com/th/id/OIP.n02-w4cRVI3ynL1fyT7XzgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$2.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B00NP79AIU",
          "product_title": "Planters Salted Cocktail Peanuts, 35 oz Jar",
          "product_price": "$5.98",
          "product_original_price": "$7.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4800,
          "product_url": "https://www.amazon.com/dp/B00NP79AIU",
          "product_photo": "https://th.bing.com/th/id/OIP.yG3hNMUYXPyYuMyxyQP1QgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$5.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B07QMFKW5V",
          "product_title": "Tide Pods Laundry Detergent Pacs, Original Scent, 81 Count",
          "product_price": "$19.99",
          "product_original_price": "$24.99",
          "currency": "USD",
          "product_star_rating": "4.9",
          "product_num_ratings": 9200,
          "product_url": "https://www.amazon.com/dp/B07QMFKW5V",
          "product_photo": "https://images.homedepot-static.com/productImages/a7159ccd-417d-440a-bc3e-4edb9e6c6528/svn/tide-laundry-detergents-003700093045-64_1000.jpg",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$18.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "12K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B07CQ2F54T",
          "product_title": "Cascade Complete Dishwasher Pods, Fresh Scent, 78 Count",
          "product_price": "$16.97",
          "product_original_price": "$19.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 6800,
          "product_url": "https://www.amazon.com/dp/B07CQ2F54T",
          "product_photo": "https://th.bing.com/th/id/OIP.YUFvhpbMvD31AzrOCq7CsgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$15.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "9K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B0863VH2P7",
          "product_title": "Nestle Coffee-mate Coffee Creamer, Original, 64 oz Bottle",
          "product_price": "$9.98",
          "product_original_price": "$11.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 5900,
          "product_url": "https://www.amazon.com/dp/B0863VH2P7",
          "product_photo": "https://i5.walmartimages.com/asr/a25ada02-9340-40c3-b906-2dac16daa7f7_1.b99ec8fe6d18f583d80bc5ac2e020cff.jpeg",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$9.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B084X5P7NC",
          "product_title": "Happy Belly Raw Wildflower Honey, 32 oz",
          "product_price": "$9.99",
          "product_original_price": "$12.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 4500,
          "product_url": "https://www.amazon.com/dp/B084X5P7NC",
          "product_photo": "https://th.bing.com/th/id/OIP.NBgfX3cN3WmTqnXrDIWgbQAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$9.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B08R5Z7D3N",
          "product_title": "StarKist Chunk Light Tuna in Water, 5 oz Can (Pack of 8)",
          "product_price": "$7.32",
          "product_original_price": "$9.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 5100,
          "product_url": "https://www.amazon.com/dp/B08R5Z7D3N",
          "product_photo": "https://th.bing.com/th/id/OIP.rKlDzSVjMSjt3_rXruH2hQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$6.50",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B089YJ4SR3",
          "product_title": "Lavazza Super Crema Whole Bean Coffee Blend, Medium Espresso Roast, 2.2 Pound",
          "product_price": "$21.39",
          "product_original_price": "$25.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 3800,
          "product_url": "https://www.amazon.com/dp/B089YJ4SR3",
          "product_photo": "https://th.bing.com/th/id/OIP.YQA761ksjvmaTnV1MoaWQQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$20.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B00I8GQJPQ",
          "product_title": "Nature's Path Organic Pumpkin Seed + Flax Granola, 11 oz",
          "product_price": "$3.49",
          "product_original_price": "$4.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 2800,
          "product_url": "https://www.amazon.com/dp/B00I8GQJPQ",
          "product_photo": "https://i5.walmartimages.com/asr/e2cd2051-0937-48a0-973c-86244a5b41f5.84240d9ee37c02e3cafaf7ce1602a8d0.png",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$3.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        }
        // Add other groceries products here
      ],
      "laptops": [
        {
          "asin": "B08X4VTR74",
          "product_title": "Acer Aspire 5 A515-56-36UT, 15.6\" Full HD Display, 11th Gen Intel Core i3-1115G4 Processor, 4GB DDR4, 128GB NVMe SSD, WiFi 6, Windows 10 Home (S Mode)",
          "product_price": "$399.99",
          "product_original_price": "$499.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 2100,
          "product_url": "https://www.amazon.com/dp/B08X4VTR74",
          "product_photo": "https://m.media-amazon.com/images/I/71AmKW4yuMS._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$379.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0865W5W6B",
          "product_title": "HP 15-dy1036nr, 15.6\" Full HD Laptop, 10th Gen Intel Core i5-1035G1, 8GB DDR4, 256GB SSD, WiFi 6, Windows 10 Home",
          "product_price": "$499.99",
          "product_original_price": "$599.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 2800,
          "product_url": "https://www.amazon.com/dp/B0865W5W6B",
          "product_photo": "https://m.media-amazon.com/images/I/71vvXGmdKWL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$479.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08Q3Q3FS7",
          "product_title": "ASUS VivoBook 15 F515 Thin and Light Laptop, 15.6\" FHD Display, Intel Core i3-1005G1 Processor, 8GB DDR4 RAM, 128GB PCIe SSD, Windows 10 Home",
          "product_price": "$399.99",
          "product_original_price": "$449.99",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 1800,
          "product_url": "https://www.amazon.com/dp/B08Q3Q3FS7",
          "product_photo": "https://i0.wp.com/www.laptopmedia.com/wp-content/uploads/2020/12/3-26-e1609250862259.jpg?fit=1500%2C1005&ssl=1",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$389.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08N6K7Y5P",
          "product_title": "Lenovo IdeaPad 3 14\" Laptop, AMD Ryzen 5 3500U Processor, 8GB DDR4 RAM, 256GB SSD, Windows 10, Abyss Blue",
          "product_price": "$479.99",
          "product_original_price": "$549.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 3200,
          "product_url": "https://www.amazon.com/dp/B08N6K7Y5P",
          "product_photo": "https://th.bing.com/th/id/OIP.NVYv8CdCWqkd8C01EEslSgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$459.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08F9TFT14",
          "product_title": "Dell Inspiron 15 3000 Laptop, 15.6\" HD Display, Intel Pentium Gold 5405U Processor, 8GB DDR4 RAM, 128GB SSD, Windows 10 Home",
          "product_price": "$379.99",
          "product_original_price": "$449.99",
          "currency": "USD",
          "product_star_rating": "4.2",
          "product_num_ratings": 1500,
          "product_url": "https://www.amazon.com/dp/B08F9TFT14",
          "product_photo": "https://th.bing.com/th/id/OIP.jxpdGKGm9ixoLAXDP7jY5AHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$369.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08QV8FY6D",
          "product_title": "HP Pavilion x360 14\" 2-in-1 Laptop, 11th Gen Intel Core i5-1135G7 Processor, 8GB RAM, 256GB SSD, Windows 10 Home",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B08QV8FY6D",
          "product_photo": "https://th.bing.com/th/id/OIP.RA2TefCUM-_JpJ70vw80JQHaFc?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0877724DZ",
          "product_title": "Apple MacBook Air 13\" with Apple M1 Chip (Late 2020)",
          "product_price": "$949.99",
          "product_original_price": "$999.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 3800,
          "product_url": "https://www.amazon.com/dp/B0877724DZ",
          "product_photo": "https://m.media-amazon.com/images/I/71TPda7cwUL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$939.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08YKPX7DW",
          "product_title": "Microsoft Surface Laptop Go - 12.4\" Touchscreen - Intel Core i5 - 8GB Memory - 128GB SSD - Sandstone",
          "product_price": "$649.99",
          "product_original_price": "$699.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 2100,
          "product_url": "https://www.amazon.com/dp/B08YKPX7DW",
          "product_photo": "https://th.bing.com/th/id/OIP.LfLIQK3Jd6JeSZTkwmivPgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$629.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08HLVSL13",
          "product_title": "Samsung Galaxy Book Flex 13.3\" Laptop, Intel Core i7-1065G7, 8GB RAM, 512GB SSD, Windows 10 Home",
          "product_price": "$1149.99",
          "product_original_price": "$1299.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 1500,
          "product_url": "https://www.amazon.com/dp/B08HLVSL13",
          "product_photo": "https://th.bing.com/th/id/OIP.BAc6_z0t_UsWbu_CzXrITgHaFj?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$1129.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0868WF8ZW",
          "product_title": "Lenovo ThinkPad E15 15.6\" Full HD Laptop, Intel Core i5-10210U, 8GB RAM, 256GB SSD, Windows 10 Pro",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 1900,
          "product_url": "https://www.amazon.com/dp/B0868WF8ZW",
          "product_photo": "https://www.bhphotovideo.com/images/images2500x2500/lenovo_20t8002aus_tp_e15_g2_ryzen_1595848.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other laptops products here
      ],
      "headsets": [
        {
          "asin": "B07RGQC7HG",
          "product_title": "Sony WH-1000XM4 Wireless Noise-Canceling Over-Ear Headphones",
          "product_price": "$348.00",
          "product_original_price": "$399.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 12000,
          "product_url": "https://www.amazon.com/dp/B07RGQC7HG",
          "product_photo": "https://www.bhphotovideo.com/images/images2500x2500/sony_wh1000xm4_b_wh_1000xm4_wireless_noise_canceling_over_ear_1582549.jpg",
          "product_num_offers": 25,
          "product_minimum_offer_price": "$329.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08F3YQ6PT",
          "product_title": "Bose Noise Cancelling Headphones 700, Over-Ear Wireless Bluetooth Headphones",
          "product_price": "$379.00",
          "product_original_price": "$399.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9500,
          "product_url": "https://www.amazon.com/dp/B08F3YQ6PT",
          "product_photo": "https://th.bing.com/th/id/OIP.IiUjJa7p1QSkMpmBzEuDKAAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$359.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07NXDPLJ9",
          "product_title": "Apple AirPods Pro",
          "product_price": "$249.00",
          "product_original_price": "$279.00",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 28000,
          "product_url": "https://www.amazon.com/dp/B07NXDPLJ9",
          "product_photo": "https://m.media-amazon.com/images/I/71zny7BTRlL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 30,
          "product_minimum_offer_price": "$239.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "15K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0863BQMF5",
          "product_title": "Sennheiser PXC 550-II Wireless Over-Ear Headphones",
          "product_price": "$229.95",
          "product_original_price": "$349.95",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 6200,
          "product_url": "https://www.amazon.com/dp/B0863BQMF5",
          "product_photo": "https://th.bing.com/th/id/OIP.zKbYvuPREuV9MEtbUisyKQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$219.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B088HM9BZB",
          "product_title": "Jabra Elite 85h Wireless Noise-Canceling Headphones",
          "product_price": "$229.99",
          "product_original_price": "$249.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 5300,
          "product_url": "https://www.amazon.com/dp/B088HM9BZB",
          "product_photo": "https://th.bing.com/th/id/OIP.WABsew5Ey2wYudrWqrXtBAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$219.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J5FYSX4",
          "product_title": "SteelSeries Arctis 7P Wireless - Lossless 2.4 GHz Wireless Gaming Headset",
          "product_price": "$149.99",
          "product_original_price": "$179.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 4100,
          "product_url": "https://www.amazon.com/dp/B08J5FYSX4",
          "product_photo": "https://th.bing.com/th/id/OIP._NfFRlNw-9Dl2K2e3X0BeAHaFj?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$139.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07VDTH16V",
          "product_title": "Corsair HS60 Pro Surround Gaming Headset - 7.1 Surround Sound Headphones",
          "product_price": "$64.99",
          "product_original_price": "$69.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 6900,
          "product_url": "https://www.amazon.com/dp/B07VDTH16V",
          "product_photo": "https://th.bing.com/th/id/OIP.2_U6sblKjM6N1RBCYyUo5AHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$59.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07SMBLK7J",
          "product_title": "Razer Kraken Gaming Headset",
          "product_price": "$69.99",
          "product_original_price": "$79.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 8800,
          "product_url": "https://www.amazon.com/dp/B07SMBLK7J",
          "product_photo": "https://th.bing.com/th/id/OIP.RWykwHxOetVvilyYB63aZwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$64.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08L8K2TJ7",
          "product_title": "HyperX Cloud Stinger Core - Headset",
          "product_price": "$79.99",
          "product_original_price": "$89.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5300,
          "product_url": "https://www.amazon.com/dp/B08L8K2TJ7",
          "product_photo": "https://th.bing.com/th/id/OIP.KdI0h_KiBGJBhtYdYO77rAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$74.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08GLXTY2C",
          "product_title": "Logitech G Pro X Gaming Headset",
          "product_price": "$129.99",
          "product_original_price": "$149.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 3900,
          "product_url": "https://www.amazon.com/dp/B08GLXTY2C",
          "product_photo": "https://th.bing.com/th/id/OIP.hKYkZyE8roE5FlAMy83KAwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$119.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other headsets products here
      ]
    }
  }
};

export default data;
